CREATE DATABASE `lseed` ;

CREATE USER 'lseed'@'localhost' IDENTIFIED BY 'GCp:rtAaN8nwTFMP';

REVOKE ALL PRIVILEGES ON * . * FROM 'lseed'@'localhost';
REVOKE GRANT OPTION ON * . * FROM 'lseed'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON * . *
TO 'lseed'@'localhost'
WITH MAX_QUERIES_PER_HOUR 0
MAX_CONNECTIONS_PER_HOUR 0
MAX_UPDATES_PER_HOUR 0

CREATE TABLE `User` (
	`ID` INT( 255 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`Name` VARCHAR( 255 ) NOT NULL ,
	`Password` VARCHAR( 255 ) NOT NULL ,
	`IsAdmin` BOOL NOT NULL ,
	INDEX ( `Name` )
) ENGINE = MYISAM ;

CREATE TABLE `plant` (
	`ID` INT( 255 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`UserID` INT( 255 ) NOT NULL ,
	`Name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,
	`Code` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,
	INDEX ( `UserID` )
) ENGINE = MYISAM ;


